# Generated by Django 5.0.2 on 2024-02-08 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lavozim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('maosh', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Xona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.PositiveIntegerField()),
                ('necha_orinli', models.PositiveIntegerField()),
                ('bosh', models.BooleanField()),
                ('hona_turi', models.CharField(choices=[('Standart', 'Standart'), ('Luxe', 'Luxe')], max_length=250)),
                ('narx', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=250)),
                ('yosh', models.PositiveIntegerField()),
                ('ish_vaqti', models.CharField(max_length=250)),
                ('tel_raqam', models.CharField(max_length=15)),
                ('manzil', models.TextField()),
                ('lavozim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.lavozim')),
                ('xona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.xona')),
            ],
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mijoz', models.CharField(max_length=250)),
                ('olingan_sana', models.DateField()),
                ('xodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.xodim')),
                ('xona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.xona')),
            ],
        ),
    ]
