# Generated by Django 5.0.2 on 2024-02-08 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xodim',
            name='xona',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.xona'),
        ),
    ]
